name    'wso2-private-paas-core'
version '1.0.0-az'
source ''
author 'WSO2 Inc'
license 'Apache License Version 2.0'
summary 'WSO2 Private PaaS puppet module'
description 'WSO2 PPaaS 1.0.0 version puppet module'
project_page ''

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
